routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes(['register' => false]);

Route::group(['middleware' => 'role:admin'], function() {

   Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('', 'DashboardController@index')->name('home');

Route::get('carga', 'EntregaController@index')->name('carga');

// Formulario de búsqueda

Route::get('buscador', 'SearchController@index')->name('buscador');

// Búsqueda por POS

Route::get('busca_pos', 'POSHistoryController@index')->name('buscapos');

// Búsqueda por rótulo

Route::get('rotulo', 'SearchController@rotulo')->name('rotulo');

// Búsqueda por serial

Route::get('serial', 'SearchController@serial')->name('serial');

// Búsqueda por POS

Route::get('pos', 'POSHistoryController@posHistory')->name('pos');

// Mantenedor de tabla maestra de modelos y marcas de equipos
Route::get('mantenedor-modelos', 'ModeloMarcaController@index')->name('modelomarca');

Route::post('agregarmarca', 'ModeloMarcaController@agregarMarca')->name('agregarmarca');

Route::post('agregarmodelo', 'ModeloMarcaController@agregarModelo')->name('agregarmodelo');

Route::get('modelo', 'ModeloMarcaController@verModelo')->name('modelo');

// Carga de planillas de entrega
Route::post('importExcelActaEntrega', 'EntregaController@procesoPlanilla')->name('importExcelActaEntrega');
// carga planillas de entrega de IBM
Route::post('importExcelActaEntregaIBM', 'EntregaIBMController@procesoPlanilla')->name('importExcelActaEntregaIBM');

// Carga de planillas de reversa
Route::post('importExcelActaReversa', 'ReversaController@procesoPlanilla')->name('importExcelActaReversa');
// Carga reversas IBM
Route::post('importExcelActaReversaIBM', 'ReversaIBMController@procesoPlanilla')->name('importExcelActaReversaIBM');

// Carga de planillas de puntos vigentes
Route::post('importExcelPuntosVigentes', 'POSCheckController@procesoPlanilla')->name('importExcelPuntosVigentes');

// Proceso que descarga la información de entrega en formato Excel de planillas de entrega

Route::get('export', 'EntregaController@descargarPlanilla')->name('export');

// Carga de planillas de bodega (IQ09)
Route::post('importExcelBodega', 'BodegaController@procesoBodega')->name('importExcelBodega');

// Carga de planilla consolidado de bodega

Route::post('importConsolidadoEntrega', 'EntregaController@procesoConsolidado')->name('importConsolidadoEntrega');

Route::post('importConsolidadoReversa', 'ReversaController@procesoConsolidado')->name('importConsolidadoReversa');

// Carga planilla de técnicos en terreno

Route::post('importTecnicos', 'ServiceController@procesoPlanilla')->name('importTecnicos');

// Vistas

Route::get('nojustificadas', 'VistasController@noJustificadas')->name('nojustificadas');

Route::get('buscar_por_guia', 'VistasController@buscarPorGuia')->name('buscar_por_guia');
Route::post('borrar_guia', 'VistasController@eliminarGuia')->name('borrar_guia');
Route::get('exportar-guias', 'vistasController@descargarTodasLasGuias')->name('exportar-guias');

Route::get('guia_recepcion', 'VistasController@porGuiaRecepcion')->name('guia_recepcion');
Route::get('guia_reversa', 'VistasController@porGuiaReversa')->name('guia_reversa');

Route::get('buscar_ibm', 'VistasController@buscarPorGuiaIBM')->name('buscar_ibm');
Route::get('guia_ibm', 'VistasController@porGuiaIBM')->name('guia_ibm');
Route::get('buscar_ibm_por_mes', 'VistasController@porMesGuiaIBM')->name('buscar_ibm_por_mes');
Route::get('buscar_ibm_por_dia/{dia}', 'VistasController@porDiaIBM')->name('buscar_ibm_por_dia');

Route::get('buscar_accesorios', 'VistasController@buscarPorGuiaAccesorios')->name('buscar_accesorios');
Route::get('buscar_accesorios_por_mes', 'VistasController@porMesGuiaAccesorios')->name('buscar_accesorios_por_mes');
Route::get('guia_accesorios', 'VistasController@porGuiaAccesorios')->name('guia_accesorios');

Route::get('buscar_ibm_accesorios', 'VistasController@buscarPorGuiaIBMAccesorios')->name('buscar_ibm_accesorios');
Route::get('buscar_ibm_accesorios_por_mes', 'VistasController@porMesGuiaIBMAccesorios')->name('buscar_ibm_accesorios_por_mes');
Route::get('guia_accesorios_ibm', 'VistasController@porGuiaIBMAccesorios')->name('guia_accesorios_ibm');

Route::get('guias_recepcion_mes', 'VistasController@porMesGuiaRecepcion')->name('guias_recepcion_mes');
Route::get('guias_reversa_mes', 'VistasController@porMesGuiaReversa')->name('guias_reversa_mes');
Route::get('guias_adexus_mes', 'VistasController@porMesGuiasAdexus')->name('guias_adexus_mes');

// Exporta dispositivos por guía

Route::get('export_recepcion/{guia}', 'VistasController@exportRecepcion')->name('export_recepcion');
Route::get('export_reversa/{guia}', 'VistasController@exportReversa')->name('export_reversa');

// Procesa toda la información subida al sistema.

Route::get('procesarTodo', 'ProcessController@procesar')->name('procesarTodo');

// BCH

Route::get('inventarioBCH', 'InvBCHController@index')->name('inventarioBCH');

Route::get('cargaInventarioBCH', 'InvBCHController@carga')->name('cargaInventarioBCH');

Route::post('procesoInventarioBCH', 'InvBCHController@proceso')->name('procesoCargaBCH');

Route::get('datatableInvBCH', 'InvBCHController@getDatatable')->name('datatableInvBCH');

Route::get('exportBCH', 'InvBCHController@export')->name('exportBCH');  

// Iniciar proceso global manualmente

Route::get('proceso_global', 'ProcessController@index')->name('proceso_global');

Route::post('procesar', 'ProcessController@procesar')->name('procesar');

// Guardar guías del sistema

Route::get('lista_guias', 'UploadDocsController@index')->name('lista_guias');

Route::get('carga_guias', 'UploadDocsController@create')->name('carga_guias');

Route::post('proceso_guias', 'UploadDocsController@store')->name('proceso_guias');

// Datatable de guias

Route::get('tabla_guias', 'UploadDocsController@getDatatable')->name('tabla_guias');

Route::get('showPDF/{guia}', 'UploadDocsController@show')->name('showPDF');

// Subida de OTDigital

Route::get('carga_ot_digital', 'OTDigitalController@create')->name('carga_ot_digital')->middleware('level:3');

Route::post('proceso_ot_digital', 'OTDigitalController@store')->name('proceso_ot_digital');

// Datos de dirección en proceso

Route::get('posdireccion', 'PosDireccionController@index')->name('posdireccion');
Route::post('upd_posdireccion', 'PosDireccionController@procesar')->name('upd_posdireccion');

// Rutas de vistas POS geográficas

Route::get('posgeo', 'POSGeoController@index')->name('posgeo');

Route::get('buscar_pos', 'POSGeoController@buscarPorComuna')->name('buscar_pos');

Route::get('posporregion/{id}', 'POSGeoController@posPorRegion')->name('posporregion');

Route::get('pos_comuna/{id}', 'POSGeoController@posPorComuna')->name('pos_comuna');

Route::get('ajax_comunas/{id}', 'POSGeoController@comunasRegion')->name('ajax_comunas');

Route::get('ajax_pos/{comuna_id}', 'POSGeoController@posComunasAjax')->name('ajax_pos');


// ZPEC

Route::get('carga_zpec', 'ZpecController@create')->name('carga_zpec');

Route::post('procesoZpec', 'ZpecController@store')->name('procesoZpec');

Route::get('zpec', 'ZpecController@index')->name('zpec');

Route::get('dataZpec', 'ZpecController@getDatatable')->name('dataZpec');

Route::get('descargar-zpec', 'ZpecController@downloadAllZpec')->name('descargarZpec');

// BCH para armado del informe tabla

Route::prefix('bch')->group(function(){
    Route::post('carga_bginfo', 'InvBCHController@procesoBginfo')->name('carga_bginfo');
    Route::post('carga_sccm', 'InvBCHController@procesoSCCM')->name('carga_sccm');
    Route::post('carga_epo', 'InvBCHController@procesoEpo')->name('carga_epo');
    Route::post('carga_rrhh', 'InvBCHController@procesoRRHH')->name('carga_rrhh');
});

// IQ09

Route::get('carga_iq09', 'IQ09Controller@create')->name('carga_iq09');

Route::post('proceso_iq09', 'IQ09Controller@store')->name('proceso_iq09');

Route::get('iq09', 'IQ09Controller@index')->name('iq09');
Route::get('iq09_datatable', 'IQ09Controller@getDatatable')->name('iq09_datatable');

// Materiales

Route::get('carga_material', 'MaterialController@create')->name('carga_material');

Route::post('proceso_material', 'MaterialController@store')->name('proceso_material');

Route::get('materiales', 'MaterialController@index')->name('materiales');

Route::get('material_datatable', 'MaterialController@getDatatable')->name('material_datatable');

// Subir accesorios

Route::post('proceso_accesorios', 'AccesorioController@store')->name('proceso_accesorios');

Route::get('no_seriados', 'AccesorioController@index')->name('no_seriados');

Route::post('accesorios_fecha', 'AccesorioController@guiasPorFecha')->name('accesorios_fecha');

// Subir accesorios no seriados IBM

Route::post('proceso_accesorios_ibm', 'AccesorioIBMController@store')->name('proceso_accesorios_ibm');



// Ruta guardar guias manualmente

Route::get('agregar_guia_pos', 'GuiaController@create')->name('add_guia');
Route::post('procesa_guia', 'GuiaController@store')->name('procesa_guia');

// Cuadro Panel

Route::prefix('cuadro-panel')->group(function(){
    Route::get('puntos-vigentes-3g', 'VistasCuadroIBMController@puntosVigentes3g')->name('puntos-vigentes-3g');
    Route::get('puntos-vigentes-gprs', 'VistasCuadroIBMController@puntosVigentesGprs')->name('puntos-vigentes-gprs');
    Route::get('puntos-vigentes-verifone', 'VistasCuadroIBMController@puntosVigentesTrafoVerifone')->name('puntos-vigentes-vef');

app/Pos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Device;

class Pos extends Model
{
    /*
     * Este modelo es específico para BancoEstado 
     * representa a la ubicación de los POS.
     * 
     * No utiliza el autoincremental. 
     */
    
    protected $table = 'pos';
    public $incrementing = false;
    
    protected $fillable = ['comuna_id'];
    
    public function devices()
    {
        //return $this->belongsToMany('App\Device', 'devices_pos')->withTimestamps();
        return $this->hasMany('App\Device');
    }
    
    public function comuna() 
    {
        return $this->belongsTo('App\Comuna');
    }
    
    public function getRegionAttribute() {
        $comuna = Comuna::find($this->comuna_id);
        if ($comuna) {
            return Region::find($comuna->region_id);
        } else {
            return null;
        }
        
    }
    
}

resources/views/busqueda/buscapos.blade.php
@extends('layouts.app')
@section('title', 'Buscar equipos por POS')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Buscar equipos por POS</div>
                
                <div class="card-body">
                     <form action="{{ route('pos') }}">
                
                <label for="pos">POS</label>
                <input type="number" name="pos" class="form-control">
                <br>
                <button type="submit" class="btn btn-success">Buscar</button>
                
                </form>
                </div>

                                
            </div>
            
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
                
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/busqueda/index.blade.php
@extends('layouts.app')
@section('title', 'Buscador de equipos')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Buscar equipos</div>
                
                
                
                <div class="card-body">
                     <form action="{{ route('pos') }}">
                
                <label for="pos">POS</label>
                <input type="number" name="pos" class="form-control">
                <br>
                <button type="submit" class="btn btn-success">Buscar</button>
                
                </form>
                </div>

                <div class="card-body">
                     <form action="{{ route('serial') }}">
                <label for="serial">Serie de equipo</label>
                <input type="text" name="serial" class="form-control">
                <br>
                <button type="submit" class="btn btn-success">Buscar</button>
                
                </form>
                </div>
                
                <div class="card-body">
                     <form action="{{ route('rotulo') }}">
                
                <label for="rotulo">Rótulo</label>
                <input type="text" name="rotulo" class="form-control">
                <br>
                <button type="submit" class="btn btn-success">Buscar</button>
                
                </form>
                </div>
                                
            </div>
            
           
                
                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/busqueda/poshistory.blade.php
@extends('layouts.app')
@isset($pos)
@section('title', 'Equipos en POS #' . $pos->id)
@endisset
@section('content')
<div class="container">
    <div class="row justify-content-center">
        
        <div class="col-md-12 m-t-15">
            
            

            @isset($devices)

            <div class="card">
                <div class="card-header">
                    <p>Equipos en POS #{{$pos->id}}</p>
                    @if ($pos->direccion)
                    <p>Ubicado en {{$pos->direccion}} en la comuna de {{$pos->comuna->name}}, región de {{$pos->comuna->region->name}}</p>
                    @endif
                    <p></p>
                </div>
                
               
                <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Serie</th>
                        <th>Modelo</th>
                        <th>Recepción</th>
                        <th>Instalación</th>
                        <th>Serie retirada</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($devices as $device)
                    <tr>
                        <th scope="row">
                            {{ $device->id }}
                        </td>
                        <td>
                            <a href="{{route('serial', ['serial' => $device->serial])}}">{{ $device->serial }}</a>
                        </td>
                        <td>
                            {{ $device->modelo->name }}
                        </td>
                        <td>
                            {{ $device->fecha_recepcion }}
                        </td>
                        <td>
                            {{ $device->fecha_instalacion }}
                        </td>
                        <td>
                            <a href="{{route('serial', ['serial' => $device->serial_prev])}}">{{ $device->serial_prev }}</a>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
                    @endisset
                    @if (!$devices->first())
                    <p class="text-center">No hay registros asociados al POS #{{$pos->id}}.</p>
                    @endif
            </div>

                </div>
            
            

                
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/busqueda/result.blade.php
@extends('layouts.app')
@section('title', 'Equipos que coinciden con ' . $input_busqueda)
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
                        
            @isset($devices)
            
            <div class="card m-t-5">
                <div class="card-header">
                    <p>Equipos que coinciden con '{{$input_busqueda}}':</p></div>
            </div>
            <div class="card">
                <div class="table-responsive">
            <table class="table table-sm">
                <thead>
                    <tr class="border-thick">
                        <th>Id</th>
                        <th>Serial</th>
                        <th>Rótulo</th>
                        <th>Modelo</th>
                        <th>GD provisión</th>
                        <th>F.provisión</th>
                        <th>F.instalación</th>
                        <th>F.reversa serie retirada</th>
                        <th>Serie retirada</th>
                        <th>GD retirada</th>
                        <th>Modelo serie retirada</th>
                        <th>POS</th>
                        <th>Servicio</th>
                        <th>Ubicación</th>
                        <th>Técnico</th>
                        
                        
                        
                        
                    </tr>
                </thead>
                <tbody>
                @forelse ($devices as $device)
                <tr class='{{isset($device->previous_device) || ($device->reusada)  ? 'table-success' : ""}}'>
                    <td>{{$device->id}}</td>
                    <td>{{$device->serial}}</td>
                    <td>{{$device->rotulo ?? ""}}</td>
                    <td>{{$device->modelo->name}}</td>
                    <td>{{$device->guia_recepcion}}</td>
                    <td>{{$device->fecha_recepcion ? $device->fecha_recepcion->format("d/m/Y") : "" }}</td>
                    <td>{{$device->fecha_instalacion ? $device->fecha_instalacion->format("d/m/Y") : "" }}</td>
                    <td>{{isset($device->previous_device->fecha_reversa) ? $device->previous_device->fecha_reversa->format("d/m/Y") : ""}}</td>
                    <td> <a href="{{$device->previous_device ? route('serial', ['serial' => $device->previous_device->serial]) : ""}}">{{isset($device->previous_device->serial) ? ($device->previous_device->serial == $device->serial ? "REUTILIZADA" : $device->previous_device->serial) : ""}} </a></td>
                    <td>{{$device->previous_device->guia_reversa ?? ""}}</td>
                    <td>{{$device->previous_device->modelo->name ?? ""}}</td>
                    <td><a href="{{$device->pos_id > 0 ? route('pos', ['pos' => $device->pos_id]) : ""}}">{{$device->pos_id > 0 ? $device->pos_id : ""}}</a></td>
                    <td>{{$device->service->name}}</td>
                    <td>{{$device->location->name != "SIN ALMACÉN" ? $device->location->name : ""}}</td>
                    <td>{{$device->technician->name != "DESCONOCIDO" ? $device->technician->name : ""}}</td>
                    
                    
                    
                    
                    
                </tr>
                @empty
                <tr>
                    <td colspan="16"> <p class="text-center">No hay registros en la base de datos.</p> </td>
                </tr>
                @endforelse
                </tbody>
            </table>
                </div>
                </div>
            
            <div class="card">
                <div class="card-header">
                    <p>Información en OT Digital</p>
                    @isset($ultima_atencion)
                    <p>Última atención registrada en OT Digital cargada: {{$ultima_atencion}}</p>
                    @endisset
                </div>
                <div class="table-responsive">
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Fecha atención</th>
                        <th>Ticket</th>
                        <th>Serie instalada</th>
                        <th>Modelo instalado</th>
                        <th>Serie retirada</th>
                        <th>Modelo retirado</th>
                        <th>Proveedor</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($otdigital as $ot)
                    <tr>
                        <td>{{$ot->fecha_atencion->format("d/m/Y") }}</td>
                        <td><a href="http://gestionactivos/cuadratura/form_ticket.php?ticket={{$ot->ticket}}" target="_blank">{{$ot->ticket}}</a></td>
                        <td>{{$ot->serie1}}</td>
                        <td>{{$ot->modelo}}</td>
                        <td>{{$ot->serie4}}</td>
                        <td>{{$ot->modelo_out}}</td>
                        <td>{{$ot->proveedor}}</td>
                        
                    </tr>
                    @empty
                    <tr>
                        <td colspan="16"> <p class="text-center">No hay registros en la base de datos.</p> </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>

            @endisset
            
            </div>
        </div>
    </div>
</div>
</div>
@endsection